services:
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=keystone_import
      - POSTGRES_USER=keystone_user
      - POSTGRES_PASSWORD=passw0rd
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d keystone_import -U keystone_user"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - ./postgresdb:/var/lib/postgresql/data
    networks:
      - import-network
  keystone_backend:
    container_name: keystone_backend
    #build: ./keystone-backend
    image: herve010/keystone-build:1.0.2
    environment:
      - FRONTEND_HOST=http://localhost:3001
      - FRONTEND_PORT=3001
      - DB_TYPE=postgresql
      - DB_DATABASE=keystone_import
      - DB_HOST=db
      - DB_USER=keystone_user
      - DB_PWD=passw0rd
      - DB_PORT=5432
    ports:
      - "3000:3000"
    volumes:
      - ./keystone-backend:/user/src/keystone-backend
    networks:
      - import-network
    depends_on:
      - db
  redis:
    container_name: redis
    hostname: redis
    image: redis:alpine3.20
    command: redis-server --appendonly yes --requirepass "paUIw93SSw0"
    ports:
      - "127.0.0.1:6379:6379"
    expose:
      - 6379
    volumes:
      - redis:/data
    networks:
      - import-network
  node_backend:
    container_name: node_backend
    #build: ./node-backend
    image: herve010/node_import:1.1.7
    restart: always
    environment:
      - PORT=8080
      - JWTSECRET=''
      - WOOMMERCE_API_URL=https://www.digitalrisedorset.co.uk/wp-json/wc/v3/
      - WOOCOMMERCE_KEY=ck_531ccb38a579fc2687c9d9460f0305f6d6cde4a3
      - WOOCOMMERCE_SECRET=cs_46373f24483a094ed9785c308b89e65cce65191e
      - WEBHOOK_SECRET=testde56l:0Pr0d1ct
      - IMPORT_BATCH_SIZE=20
      - WOOCOMMERCE_WEBHOOK_SECRET=testde56l:0Pr0d1ct
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=paUIw93SSw0
      - REDIS_USERNAME=default
      - FS_CACHE_FOLDER=fs_cache
    ports:
      - "8080:8080"
    volumes:
      - ./node-backend:/user/src/node-backend
    expose:
      - 8080
    networks:
      - import-network
    depends_on:
      - redis
  react_frontend:
    container_name: react_frontend
    #build: ./react-frontend
    image: herve010/react_import:1.0.4
    restart: always
    environment:
      - REACT_APP_KEYSTONE_HOST=http://localhost:3000
      - REACT_APP_KEYSTONE_PORT=3000
      - REACT_APP_NODE_HOST=http://localhost:8080
      - REACT_APP_NODE_PORT=8080
      - REACT_APP_MAGENTO_HOST=http://magentodevelop24.com
      - PORT=3001
    ports:
      - "3001:3001"
    volumes:
      - ./react-frontend:/user/src/react-frontend
    expose:
      - 3001
    networks:
      - import-network
networks:
  import-network:
    driver: bridge
volumes:
  redis:
  postgresdb:
