services:
#  db:
#    image: mysql:8.0.37
#    restart: always
#    environment:
#      MYSQL_DATABASE: 'keystone_import'
#      MYSQL_USER: 'keystone_user'
#      MYSQL_PASSWORD: 'passw0rd'
#      MYSQL_ROOT_PASSWORD: 'passw0rd'
#    ports:
#      - '3306:3306'
#    expose:
#      - '3306'
#    volumes:
#      - mysqldb:/var/lib/mysql
  redis:
    container_name: redis
    hostname: redis
    image: redis:alpine3.20
    command: redis-server --appendonly yes --requirepass "paUIw93SSw0"
    ports:
      - "127.0.0.1:6379:6379"
    expose:
      - 6379
    volumes:
      - redis:/data
    networks:
      - import-network
  keystone_backend:
    container_name: keystone_backend
    image: herve010/keystone-build:0.0.7
    environment:
      - FRONTEND_HOST=localhost:3001
      - FRONTEND_PORT=80
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PWD}
      - DB_PORT=${DB_PORT}
      #restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./keystone-backend:/user/src/keystone-backend
    networks:
      - import-network
#    depends_on:
#      - db
  node_backend:
    container_name: node_backend
    build: ./node-backend
    restart: always
    environment:
      - PORT=8080
      - JWTSECRET=''
      - WOOMMERCE_API_URL=https://www.digitalrisedorset.co.uk/wp-json/wc/v3/
      - WOOCOMMERCE_KEY=${WOOCOMMERCE_KEY}
      - WOOCOMMERCE_SECRET=${WOOCOMMERCE_SECRET}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - IMPORT_BATCH_SIZE=20
      - WOOCOMMERCE_WEBHOOK_SECRET=${WOOCOMMERCE_WEBHOOK_SECRET}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USERNAME=default
      - FS_CACHE_FOLDER=fs_cache
    ports:
      - "8080:8080"
    volumes:
      - ./node-backend:/user/src/node-backend
    expose:
      - 8080
    networks:
      - import-network
    depends_on:
      - redis
  react_frontend:
    container_name: react_frontend
    build: ./react-frontend
    restart: always
    environment:
      - REACT_APP_KEYSTONE_HOST=import-keystone.digitalrisedorset.co.uk
      - REACT_APP_KEYSTONE_PORT=3000
      - REACT_APP_NODE_HOST=import-node.digitalrisedorset.co.uk
      - REACT_APP_NODE_PORT=8080
      - REACT_APP_MAGENTO_HOST=https://demo.digitalrisedorset.co.uk/
      - PORT=3001
    ports:
      - "3001:3001"
    volumes:
      - ./react.txt-frontend:/user/src/react.txt-frontend
    expose:
      - 3001
    networks:
      - import-network
networks:
  import-network:
    driver: bridge
volumes:
  redis:
#volumes:
#  mysqldb:
