import Head from "next/head";
import {Map} from "@/pages/mapping/components";

export default function MapPage() {
    return (
        <>
            <Head>
                <title>Mapping</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Map />
            </main>
        </>
    );
}
