import Head from "next/head";
import {Sign} from "@/pages/user-authentication/components/Sign";

export default function SignInPage() {
    return (
        <>
            <Head>
                <title>Sign In</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Sign />
            </main>
        </>
    );
}