FROM node:18-alpine

RUN apt-get update \
    && apt-get install -y curl

RUN curl -o- -L https://yarnpkg.com/install.sh | bash
RUN yarn global add yo generator-keystone

WORKDIR /app
COPY package.json ./
COPY ./ ./
COPY .env ./.env
COPY .keystone ./.keystone
