import Head from "next/head";
import {GetCatalogSourceAttribute} from "@/pages/catalog-source/components/MainMappingArea/GetCatalogSourceAttribute";
import {GetIgnoredAttribute} from "@/pages/catalog-source/components/IgnoreFieldArea/GetIgnoredAttribute";
import {MappingScreen} from "@/pages/global/styles/MappingScreen";
import {useRouter} from "next/router";
import {useFlashMessage} from "@/state/flassMessageState";

export default function MapPage() {
    const { query } = useRouter();
    const { addFlashMessage } = useFlashMessage()
    const { initialAttribute, matchingAttribute } = query;

    //addFlashMessage(`The catalog attribute "${initialAttribute}" is matched with the magento attribute "${matchingAttribute}"`)

    return (
        <>
            <Head>
                <title>Catalog Source</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <MappingScreen>
                    <div className="fields">
                        <GetCatalogSourceAttribute />
                    </div>
                    <GetIgnoredAttribute />
                </MappingScreen>
            </main>
        </>
    );
}