apiVersion: apps/v1
kind: Deployment
metadata:
  name: keystone-backend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keystone-backend
  template:
    metadata:
      labels:
        app: keystone-backend
    spec:
      containers:
        - name: keystone-backend
          image: herve010/keystone-build:1.0.2
          env:
            - name: FRONTEND_HOST
              value: "http://import-any-source.digitalrisedorset.co.uk"
            - name: FRONTEND_PORT
              value: "3001"
            - name: DB_TYPE
              value: "postgresql"
            - name: DB_DATABASE
              value: "keystone_import"
            - name: DB_HOST
              value: "postgres-srv"
            - name: DB_USER
              value: "keystone_user"
            - name: DB_PWD
              value: "passw0rd"
            - name: DB_PORT
              value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: keystone-backend-srv
spec:
  selector:
    app: keystone-backend
  ports:
    - name: keystone-backend
      protocol: TCP
      port: 3000
      targetPort: 3000
