apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.37
          env:
            - name: MYSQL_DATABASE
              value: "keystone_import"
            - name: MYSQL_USER
              value: "keystone_user"
            - name: MYSQL_PASSWORD
              value: "passw0rd"
            - name: MYSQL_ROOT_PASSWORD
              value: "passw0rd"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-srv
spec:
  selector:
    app: mysql
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
